spioupiou/is-kondo

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
added same container on "new" and "edit" page just like the "login" page for consistency
> added container-row-col div on new / edit page

- config/routes.rb
We might not have time to work on destroy or the possibility for the user to amend his booking but I still created those routes with resources! Hope that looks correct!
> The routes are done

- app/controllers/bookings_controller.rb
- app/controllers/kondos_controller.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/kondos_controller_test.rb
Created bookings_controller, kondos_controller and respective views folder
s
> Created bookings_controller and kondos_controller 

- Gemfile
- Gemfile.lock
- db/seeds.rb
I added seed data for testing, Feel Free to change the data, I also added the FAKER gem for randomize Details and Summary of our Kondos
> added seeds and Faker gem for randomize details and summary

- app/models/kondo.rb
- db/seeds.rb
Created some bookings seeds and I also added one association - I think a kondo should have many bookings
> Bookings seeds

- app/views/kondos/index.html.erb
> made kondos names a link to its show page for easy testing/access

- app/views/kondos/index.html.erb
- app/views/pages/home.html.erb
I also added a link at home page to index page for easy testing/accessabilty
> Added at home

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- app/views/kondos/show.html.erb
Added a basic button in show page to redirect the user to the bookings/new page
Made a simple form for the user to input the date of booking
Some pseudo code for the create > Once the user fills the date, retrieve the date, kondo_id, user_id to create a new booking and save
> function new in bookings_controller

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
Coded the 'create' method in bookings_controller + private method to generate a new date with all the integers returned by simple_form. The style is not so elegant - if you have any suggestion please feel free to comment! :)
> Create function in bookings_controller

- .gitignore
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220125112259_create_active_storage_tables.active_storage.rb
- db/schema.rb
Added necessary configuration for cloudinary
> Cloudinary setup

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/kondos_controller.rb
- app/models/application_record.rb
- app/policies/application_policy.rb
Hey guys! Creating a pull request for pundit. I did the basic installation but did not add any policies as of yet.
> Added pundit gem and basic configs

- app/controllers/application_controller.rb
- app/models/application_record.rb
Got rid of a line of code which caused the app to break.
> removed an error from application_record

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
Added the prefectures in signup/edit account :)
> Finally the prefectures work

- app/models/kondo.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/kondos/_form.html.erb
Updated Kondo model so that one picture is attached + basic form template for Kondo creation
> Updated Kondo model + basic form with photo

- app/views/kondos/index.html.erb
removed .all from kondos iteration in the views
> removed  from iteration

- app/controllers/application_controller.rb
- app/views/kondos/index.html.erb
change the kondo-index view for better testing and temporarily commented out `after_action` at `app/controllers/application_controller.rb` for temporary access
> Index page

- Gemfile
- app/controllers/kondos_controller.rb
- app/models/application_record.rb
- app/policies/kondo_policy.rb
- app/views/kondos/index.html.erb
- test/policies/kondo_policy_test.rb
Hello everyone! Okay, so I've changed a few things around. Index page should be working now. I've added an H1 to it just for verification that it is working. (Also, I am going to delete my first PR and the other multiple branches which has the same thing)
> Pundit updates

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/components/_card.html.erb
- app/views/components/_searchBar.html.erb
- app/views/kondos/index.html.erb
- app/views/kondos/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Added search bar at homepage
Added Components/_card.html.erb
Implemented card components on Home and Show page
Added CSS variable `$kondo` and `$kondo2` for color scheme
Made little changes on Navbar
> Search bar

- app/controllers/kondos_controller.rb
added code on Kondo index controller for search function
> Search form at homepage

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20220125112310_add_role_to_users.rb
- db/schema.rb
- db/seeds.rb
Was meant to only be for migration but went ahead and implemented everything: enum for roles, seeding, user signup form.
Notes on users
- current users we're using will be providers, same credentials
- new users will be renters just add `r` at the beginning of your email and use the same password
Notes on user model: now we can do methods like this
```ruby
[1] pry(main)> q = User.last
User Load (0.8ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<User id: 27, email: "rshante@email.com", created_at: "2022-01-25 16:03:10", updated_at: "2022-01-25 16:03:10", first_name: "Shante", last_name: "Johnson", prefecture: nil, role: "renter">
[2] pry(main)> q.renter?
=> true
[3] pry(main)> q.provider?
=> false
[4] pry(main)> User.renter
User Load (1.0ms) …
```
> Migration for user roles

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- db/seeds.rb
This will allow us to do the following with booking model: get bookings of certain status, check status of the booking, update status of the booking.
```ruby
[3] pry(main)> Booking.first.confirmed?
Booking Load (0.9ms)  SELECT "bookings".* FROM "bookings" ORDER BY "bookings"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> true
[4] pry(main)> Booking.first.waiting?
Booking Load (0.9ms)  SELECT "bookings".* FROM "bookings" ORDER BY "bookings"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> false
[5] pry(main)> Booking.confirmed
Booking Load (0.9ms)  SELECT "bookings".* FROM "bookings" WHERE "bookings"."status" = $1  [["status", "confirmed"]]
=> [#<Booking:0x00007ff2710b4b20
id: 69,
user_id: 47,
kondo_id: 179,
status: "confirmed",
booked_date: Thu, 27 Jan 2022 00:35:38 UTC +00:00,
created_at: Thu, 27 Jan 2022 …
```
> added status via enums for bookings

- db/schema.rb
- db/seeds.rb
Hey Team So I pull our latest master repo then I tried to db:seed it, There's an error that the User doesn't have "prefecture" in it so I went ahead and added it
> added prefecture to user-seed

- app/views/layouts/application.html.erb
very small change just to make the tab title better
> minor update for better tab title

- db/migrate/20220127115011_change_booked_date_from_date_time_to_date.rb
Also made sure that a booking always has a booked_date.
> migration to update Booking model's booked_date from datetime to just date

- app/controllers/kondos_controller.rb
- app/models/user.rb
- app/views/kondos/index.html.erb
- app/views/kondos/show.html.erb
- db/seeds.rb
@carlnoval hey man I fixed it :)
> Kondo show index page

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/new.html.erb
- db/schema.rb
Added validations for empty date, invalid format. The date must be at least three days from now and it cannot be too far in time. Please let me know if you have other ideas of validation!
(FYI - I remove the strong params because this was causing crazy errors when testing the validations... As i only use params[:booking][:booked_date] to build the booking, I trust that the user cannot inject other unpermitted params)
> Booking without dates

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/kondos_controller.rb
- app/models/user.rb
- app/views/bookings/edit.html.erb
- app/views/components/_card.html.erb
- app/views/kondos/index.html.erb
- app/views/kondos/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
A adjusted some of the codes,  I changed `#date_params` to `#booking_params` because `:status` needed to be added at the strong params method. Also added some other things please refer to the code, and I styled the kondo-show page for the renter and provider
Renter Show-page:
Provider Show-page
> Style kondo show

- app/controllers/kondos_controller.rb
- app/views/kondos/index.html.erb
- app/views/kondos/show.html.erb
Unauthenticated users can see index and show pages
> Test branch

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Banner font

- app/views/devise/sessions/new.html.erb
small pr, small login button annoys me
> make login button more clickable

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_kondo-show.scss
- app/controllers/bookings_controller.rb
- app/controllers/kondos_controller.rb
- app/views/bookings/new.html.erb
- app/views/kondos/show.html.erb
> Put booking form in showpage

- app/controllers/bookings_controller.rb
- config/routes.rb
> change routes

- config/environments/production.rb
> cloudinary on prod

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
**@TEAM**
You must add these new env variables in your .env file so the brand logo and homepage background will work
```
HOME_BACKGROUND=https://res.cloudinary.com/djlvhfuba/image/upload/v1643110748/development/interior_ncfcmy.png
BRAND_LOGO=https://res.cloudinary.com/djlvhfuba/image/upload/v1643111463/development/kondo-logo.png
```
> Make static images work on prod

- app/views/kondos/show.html.erb
small pr, fixed a bug for non logged in users
> show booking for unauthenticated user

- app/models/booking.rb
- app/views/bookings/index.html.erb
> fixed bookings-index for renters changed status color

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_notification.scss
- app/views/components/_cardProvider.html.erb
- app/views/kondos/index.html.erb
added Notification, for now it indicates count of the bookings of each kondo, We'll use AJAX for this later on
> Notification icon

- app/views/pages/home.html.erb
- config/environments/production.rb
> more tries :(

- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- db/schema.rb
I added footer, color is plain for now, can change later, if you have something in mind what to put in the footer, please feel fre to add or change it
> added footer

- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/kondos_controller.rb
- app/policies/booking_policy.rb
- app/views/kondos/show.html.erb
- db/schema.rb
Please try to pull this branch and go through the journey of 1/ unauthenticated user 2/ provider 3/ renter. I think I managed to solve the authorization issues but a double check would be highly appreciated!
> Pundit for renters

- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- app/views/components/_cardRenter.html.erb
Added Filter for booking index
You'll notice that active button will not persist, ( I only set it to `a:hover` will add ajax later, as simple javascript won't do here because when you click one of filter, it refreshes the page.
> Group bookings

- app/views/components/_cardRenter.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- db/schema.rb
add spacing as per Yann's suggestion
> Add spacing to cards

- Gemfile
- config/initializers/geocoder.rb
Initial setup for geocoder so that we can add addresses and coordinates in bookings
> Geocoder setup

- app/controllers/profiles_controller.rb
- app/views/profiles/show.html.erb
- config/routes.rb
- test/controllers/profiles_controller_test.rb
Created a profile controller and routes for profile
> created profile controller and routes

- app/assets/stylesheets/components/_filter.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/bookings/index.html.erb
- app/views/components/_cardRenter.html.erb
- app/views/kondos/edit.html.erb
added edit page to update kondo
> Edit kondo

- db/seeds.rb
This seed improvement also serves as a prep to make sure that we have clean data when implementing Reviews.
> seed improvement, prevent user from booking the same kondo twice

- Gemfile
- app/models/booking.rb
- config/initializers/geocoder.rb
- db/migrate/20220201123635_add_address_to_bookings.rb
> Addresses on bookings

- app/models/booking.rb
- db/migrate/20220201123635_add_address_to_bookings.rb
- db/seeds.rb
Added addresses and coordinates in the bookings seeds!
I also restricted the number of prefectures when creating Kondos.
> Booking address seeds

- app/controllers/kondos_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/booking.rb
- app/views/kondos/index.html.erb
- app/views/layouts/application.html.erb
- db/migrate/20220201123635_add_address_to_bookings.rb
- db/seeds.rb
- package.json
I found a super useful trick: you can use an array of values to make a query with active record :D
`Model.where(id: [array of values])`
> Draw the map

- app/javascript/packs/application.js
- app/javascript/plugins/sweet_alert.js
- app/views/kondos/show.html.erb
- package.json
Added Sweet alert, Need to install sweet alert plugin just run `yarn add sweetalert2` on your terminal
> added sweet alert when renter book a kondo

- app/javascript/plugins/init_mapbox.js
- app/views/kondos/index.html.erb
- db/seeds.rb
I added the markers (and also corrected the seeds, because Kanda was showing up in Russia... I replaced with Chiyoda instead)
> Add markers to map

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/kondos_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/kondos/_info_window.html.erb
Added a simple window with the booked_date, name of the renter and name of the kondo
> Add info windows

- app/controllers/application_controller.rb
- app/controllers/profiles_controller.rb
- app/models/profile.rb
- app/models/user.rb
- app/views/profiles/show.html.erb
- app/views/shared/_sidebar.html.erb
- db/migrate/20220202111107_update_profile_in_users.rb
- db/migrate/20220202114752_remove_user_id_from_profile.rb
- db/schema.rb
- db/seeds.rb
Added a profile page (with bare minimum info),
created basic seeds for the profile page
Added a link to the sidebar (for the profile)
created a new migration file for the profile
updated the User and Profile model
> added profile page

- app/controllers/profiles_controller.rb
Quick fix to allow users who are not logged in to see the profiles!
> Allow profile access to unauthenticated users

- app/controllers/bookings_controller.rb
- app/views/kondos/_booking_form.html.erb
Created a new PR for preventing reload. This should be up-to-date with current master branch.
> prevents reload and updated with current master

- app/controllers/kondos_controller.rb
- app/views/kondos/_submitted_reviews.html.erb
- app/views/kondos/show.html.erb
Just have to submit a review after this
> Show reviews from kondo booking

- app/models/kondo.rb
Limited the number of prefectures in the search filter
> Restricted search

- app/views/kondos/show.html.erb
> Allow visitor see kondo
